### ISSUE TITLE
prefix needs rework

### ISSUE THREAD

**Issue by con-ssc** [jlattimer/CRMVSCodeJSSnippets#3]
Don't use that long prefixnames, they will get cut off as soon as you type a dot. Better find a really short version for them :)

**Comment by jlattimer** [comment]
Yeah the long names aren't that great. The long ones turned out to be for the process and grid functions. 

Do you think shortening them to something like this would be better? I'm already doing something similar with Xrm.execObj to represent using the execution context related functions.

From: Xrm.Page.data.process.getActiveProcess().getStages().get().getSteps().get().getAttribute()
To: Xrm.Process.getStages().getSteps().getAttribute()

or 
From: Xrm.Page.getControl().getGrid().getRows().get(rowindex).getData().getEntity().getEntityName()
To: Xrm.Grid.getRows().getData().getEntity().getEntityName()

**Comment by con-ssc** [comment]
I think the only possible way would be mnemonics and no dots. As soon as you reach the dot the quick suggestions will kick in. It is really hard to come up with abbrevations for those long and complex commands, but remember, there is also the description so the prefix can be a bit cryptic. Maybe go with the first letter or something and keep the xrm maybe.
From: Xrm.Page.data.process.getActiveProcess().getStages().get().getSteps().get().getAttribute()
To: xrmpdpgapgsggsgga what an ugly prefix :)  but usually you don't type the full one I guess.

**Comment by jlattimer** [comment]
Ended up removing the periods and shortening them down to a few categories and removing any extraneous parts that didn't matter for identification purposes.
